name: Get affected files
description: Check the affected files in the pull request to then tun "nx affected" commands
runs:
  using: composite
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4

# Note: When we move to self hosted runners, we should add more configuration
# as is described here https://github.com/nrwl/nx-set-shas?tab=readme-ov-file#self-hosted-runners
