name: Get affected files
description: Sets the base and head SHAs required for the `nx affected` commands in CI
runs:
  using: composite
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4
