name: Prepare monorepo tooling
description: Install dotnet and Node dependencies
runs:
  using: composite
  steps:
    - name: Install dot net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0

# TODO/optimsation: add Nx cache in Azure storage: https://nx.dev/nx-api/powerpack-azure-cache

    - name: Install Node dependencies 📦
      shell: bash
      run: pnpm install
