name: PR validation
run-name: ${{ github.actor }} is running PR validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - .github/workflows/pr.yaml
      - applications/**/*
      - libraries/**/*
  merge_group:
    types: [checks_requested]

permissions:
  contents: 'read'
  actions: 'read'

concurrency:
  cancel-in-progress: true
  group: '${{ github.workflow }} @ ${{ github.ref }}'

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧰 Prepare monorepo tooling
        uses: ./.github/actions/prepare

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🧰 Prepare monorepo tooling
        uses: ./.github/actions/prepare

      - name: 🔍 Get affected files
        uses: ./.github/actions/get-affected-files

      - name: 🧪 Test
        run: pnpm nx affected -t test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧰 Prepare monorepo tooling
        uses: ./.github/actions/prepare

      - name: 🔍 Get affected files
        uses: ./.github/actions/get-affected-files

      - name: 🧹 Lint
        run: pnpm nx affected -t lint
